### PR TITLE
RTL revisions, language switcher alignment, Arabic type styles

### PR DESCRIPTION
**Pull request by blms**
## In this PR

- Per #1127:
  - Fix all listed RTL CSS problems in that issue
  - Wrap menu item link text nodes in `span` to prevent flex row-wrap weirdness
- Per #1113:
  - Fix alignment of items in language switcher
- Per #1138:
  - Add new Arabic fonts, type styles

## Questions

- Seems Lighthouse is failing on `total-byte-weight`, probably due to the new Arabic fonts. Should we adjust the tolerance for that, or find some way to mitigate?

### CODE REVIEW

**Comment by blms** [comment]
@rlskoeser Still failing that lighthouse `total-byte-weight` assertion, even with the conditional 🫤

I did notice that the document detail page and search results perform the worst, which makes sense since they are both now loading the second transcription font for Arabic… but we don't actually use that font yet, since we set [all transcriptions](https://github.com/Princeton-CDH/geniza/blob/36bcbf82839dafd6cae3dfc94c2f1bdd6fcd4b70/sitemedia/scss/components/_transcription.scss#L896) to use the Hebrew font for now (we have a [TODO](https://github.com/Princeton-CDH/geniza/blob/36bcbf82839dafd6cae3dfc94c2f1bdd6fcd4b70/sitemedia/scss/base/_typography.scss#L295) about it). How should we handle that?

But, even with that, the other pages are still just barely failing their assertions, and I'm not sure why! Maybe it's sufficient for those to adjust the `total-byte-weight` tolerances slightly.

**Comment by rlskoeser** [comment]
@blms thanks for investigating. I'm ok with increasing our tolerance (and documenting why!) or making it a warning instead of an error.

**Comment by blms** [comment]
@rlskoeser Done—feel free to take a quick look at the code if you have time, or I can just go ahead and merge since it's mostly CSS.

**Comment by rlskoeser** [comment]
@blms thanks — glanced at the diff, I think you can go ahead and merge

**Pull request merged**
