### PR TITLE
#401 - Improve mirador display

### PR DESCRIPTION
**Pull request by blms**
## review notes

- Not much code review needed here, just not sure how to handle comparing this with PR #546, the Mirador replacement design. Leave both unmerged?

## What this PR does

- Regenerates UI/UX test fixtures with updated data (especially transcriptions!)
- Per #401:
  - Improves spacing for Mirador on desktop and mobile
  - Resizes some Mirador components on mobile such that it is usable
- Per #512:
  - Enables Mirador dark mode when dark mode is active on the site

## dev notes
- Still wasn't able to resolve Mirador not showing transcriptions in Percy from #512. Thought it might be the test fixtures but still not working!

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
I tried this locally and couldn't didn't see any difference in mirador when I switched to dark mode — am I missing something?

The updated styles do improve things some. 

I think if we stick with mirador we should move the thumbnails to the bottom instead of the side, they take up too much room on mobile.  (Or maybe suppress them on mobile?)

**Comment by blms** [comment]
@rlskoeser 
> I tried this locally and couldn't didn't see any difference in mirador when I switched to dark mode — am I missing something?

That's odd—check out [Percy](https://percy.io/2cf28a24/geniza/builds/15290606), it's even working there! Maybe a JS cache issue?

> I think if we stick with mirador we should move the thumbnails to the bottom instead of the side, they take up too much room on mobile. (Or maybe suppress them on mobile?)

When they're set to bottom by default they cover up a big chunk of the transcription, which is also bad on mobile! I set them to be off by default on mobile, just based on the screen size on page load. (So you'd have to reload when testing this in the browser)

**Comment by blms** [comment]
@rlskoeser Maybe it makes sense to merge this one since it's just updates to Mirador, which is already present. Then we can leave the other one open for decision-making purposes. What do you think?

**Comment by rlskoeser** [comment]
Tested again — you're right, I must have had something cached. I see the dark theme now. And now that I know to reload for mobile, I see the adjustments you made (and makes sense to configure it on page load). 

I agree, we may as well merge these improvements in.

**Pull request merged**
