### PR TITLE
Revert sort listbox to <select> in search form (#1089)

### PR DESCRIPTION
**Pull request by blms**
## In this PR

- Per #1089:
  - Remove `SelectDisabledMixin` and `RadioSelectWithDisabled`, and revert form widget to default `select` element
  - Remove details/summary/button from HTML and revert to form default widget; add icon for caret-down (presentation only)
  - Remove Stimulus logic for control of the custom listbox, and adapt Stimulus logic for "relevance" option enabling/disabling
  - Adapt CSS for `select` element and Phosphor icon

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
The styles look good. Wish we had done this from the outset, and will remember in future.

Why did you remove `SelectDisabledMixin` ? That logic hasn't changed and still pertains.  (Were we even using it, since we weren't using a `<select>` element?)

**Comment by blms** [comment]
@rlskoeser We were not using it, but according to the docstring it is actually meant for radio or checkbox select widgets. 

I think it was vestigial, we should have removed it back when we removed this block in c4f237b16ad50e0d12016ef271d65a862ac3032a. (relevant discussion in https://github.com/Princeton-CDH/geniza/pull/353)

https://github.com/Princeton-CDH/geniza/blob/e567519726221b31ee6818d25fff9718ef22e55c/geniza/corpus/forms.py#L64-L75

**Comment by rlskoeser** [comment]
> @rlskoeser We were not using it, but according to the docstring it can be used for radio or checkbox select widgets.
> 
> I think it was vestigial ...


It was vestigial in our previous implementation but useful in our fixed one now. I expect it to work the same way as a mixin for the `Select` widget, I think the choice field logic is the same for all of the widgets.

I'd prefer to have the logic server side and not just in the javascript, and I think th existing code should get us very close if not all the way there

**Comment by blms** [comment]
I see, thanks! I will give it a try with that `__init__` code restored.

**Comment by blms** [comment]
Done, it is working perfectly! Thanks for the catch. I also gave you co-author credit since all of that logic was yours to begin with 😆

**Review by rlskoeser — APPROVED** [review]

**Pull request merged**
