### PR TITLE
#451 - Implement new pagination designs

### PR DESCRIPTION
**Pull request by blms**
## Visual review notes

[Latest Percy build](https://percy.io/2cf28a24/geniza/builds/15062034)

In scope:
- Pagination controls, mobile and desktop, light and dark modes

## What this PR does

- Per #451:
  - Implements new pagination designs on mobile and desktop

### CODE REVIEW

**Comment by gissoo** [comment]
@blms do you know why this is happening on safari? Everything else looks good. 

Screen Shot 2022-01-19 at 6 35 17 PM

**Comment by gissoo** [comment]
also, unrelated but this looks scary: :D Screen Shot 2022-01-19 at 6 42 20 PM

**Comment by blms** [comment]
> @blms do you know why this is happening on safari? Everything else looks good.

Thanks! I'm not sure why it's happening, first noticed it in #466. Rebecca and I weren't able to replicate in our own copies of Safari so we just chalked it up to Percy.

**Comment by mrustow** [comment]
Ideally long shelfmarks within joins like the above (however or wherever they end up appearing) should be broken not in the middle of the shelfmark but either before or after the + : 
Bodl. MS heb. f 34/41
+ Bodl. MS heb. f 34/40
+ Bodl. MS heb. f 34/39

or 

Bodl. MS heb. f 34/41 +
Bodl. MS heb. f 34/40 +
Bodl. MS heb. f 34/39

@richmanrachel do you have a preference between those two options? I _think_ I prefer the first one.

**Comment by blms** [comment]
@mrustow @richmanrachel @gissoo I think this pertains to #493 which is still open so we can move this discussion there. If a new issue needs to be created we can do that instead, though!

**Pull request merged**
