### PR TITLE
a11y fixes

### PR DESCRIPTION
**Pull request by rlskoeser**

### CODE REVIEW

**Comment by blms** [comment]
@rlskoeser Should this be merged per https://github.com/Princeton-CDH/geniza/issues/1087?

**Comment by rlskoeser** [comment]
> @rlskoeser Should this be merged per #1087?

whoops, wow how long has this been hanging out unmerged? 😅 🤦‍♀️ 

let me check for conflicts and then yes, let's get it merged

**Comment by rlskoeser** [comment]
@blms I rebased from develop and thought I specified that develop changes should take precedence - not sure why the message files are still showing modifications. Any thoughts? Should I start over with a new branch from develop and cherry-pick commits?

**Comment by blms** [comment]
@rlskoeser Not sure either! That works; probably wise since this is a branch from 2022 anyway.

**Comment by rlskoeser** [comment]
@blms it's possible I never merged because of the lighthouse error...

**Comment by blms** [comment]
@rlskoeser Ooh, that does make sense. Seems like it might be erroring out on one of the changes to the translated `default` template tags? Not sure why that would throw a server error…

**Pull request merged**
