### PR TITLE
Add ISSN to footer (#1195)

### PR DESCRIPTION
**Pull request by blms**
## In this PR

- Per #1195:
  - Add ISSN to footer, matching S&co styles
  - Fix resulting lighthouse issue

## Questions

- Does ISSN need a translation? (I assumed yes!)
- To match the S&Co site I needed to make a few other changes to the layout. Can you [take a quick look at Percy](https://percy.io/2cf28a24/geniza/builds/22188898/), and see if the change is acceptable?

### CODE REVIEW

**Review by rlskoeser — APPROVED** [review]
Looks great to me. Thanks for figuring out a way to adjust the design to accommodate the change.

I'm not sure about translating ISSN, but seems reasonable to me to flag it! Maybe crowdin will have suggested translations we can use or adapt.

**Comment by rlskoeser** [comment]
@blms would you regenerate the translation files before merging?

**Comment by blms** [comment]
@rlskoeser Sure, thanks for the reminder! I definitely haven't been doing that lately 😓 

Any idea why / if it matters that it's now prepending every path with `geniza/` in the translation files? I'm running it from the same place as usual.

**Comment by rlskoeser** [comment]
> @rlskoeser Sure, thanks for the reminder! I definitely haven't been doing that lately 😓

I haven't run it in a while lately either, hard to remember...

> Any idea why / if it matters that it's now prepending every path with `geniza/` in the translation files? I'm running it from the same place as usual.

Our devnotes say you need to run it from inside the geniza directory — when I run it that way locally I don't get the `geniza/` path that you did

**Comment by blms** [comment]
> Our devnotes say you need to run it from inside the geniza directory — when I run it that way locally I don't get the geniza/ path that you did

Wow, great catch! I should read the dev notes more. I guess I must have done that in the past, so I _didn't_ actually run it int he same directory as usual 😅

**Pull request merged**
